# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def sumOfEvenFibsBelowLimit(limit):
    fibFollow = 1
    fibLead = 2
    evenFibSum = 0
    fibFollowPlaceholder = 0
    fifteenSum = 0

    while fibLead <= limit:
        if (fibLead%2) == 0:
            evenFibSum = fibLead + evenFibSum 
        fibFollowPlaceholder = fibLead 
        fibLead = fibLead + fibFollow
        fibFollow = fibFollowPlaceholder
    
    return evenFibSum
print(sumOfEvenFibsBelowLimit(4000000))
